# This file was generated by GoReleaser. DO NOT EDIT.
cask "invar" do
  version "1.0.29"

  on_macos do
    on_arm do
      sha256 "445013b73757eceb7f8fc94dda3c88e5568ff83080ded970601ff11fc63f78d8"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "73baf526683fdede48ca9269e8fbf627c12b472180ca5d2a3585548674921feb"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b100e5b64eb22bde793def6de61acfe6311b543c6de0b36dccb1fdf23130875b"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_x86_64.tar.gz"
    end
  end

  name "invar"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invar"

  # No zap stanza required
end
