# This file was generated by GoReleaser. DO NOT EDIT.
cask "invar" do
  version "1.0.28"

  on_macos do
    on_arm do
      sha256 "05219221b16b8c7d6fd64a8ee3cfc03b713b8449dd8bbc8c15c1abc09578b2fe"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "013e9b8bcca913cae743d8f5a3dffb05813544f0400f06d670a3e6533d410404"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0fdc4e685adcbab29352152d5cccecf90192d4b08af05a39c189ff6cc9bfd4ac"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_x86_64.tar.gz"
    end
  end

  name "invar"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invar"

  # No zap stanza required
end
