# This file was generated by GoReleaser. DO NOT EDIT.
cask "invar" do
  version "1.0.27"

  on_macos do
    on_arm do
      sha256 "34e76f84598fd277f65f3e155f7735acd4d732da8c9322aaa6e4e64f0fae23b7"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "840149fc586a16d2f04528b2d8fee9409dd19730330740683967df64de30e2d1"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "94addda485e63dd8535789799670fcf9c27a9124e8ec96f4d8b7de991a3e4b97"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_x86_64.tar.gz"
    end
  end

  name "invar"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invar"

  # No zap stanza required
end
